spring:
  application:
    name: spring-logstash
  profiles:
    active: default
app:
  version: 0.1.1

server:
  port: 8484

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "prometheus" ]
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

logging:
#  logging:
#    logback:
#      customFields: '{"app_name":"${spring.application.name}","app_version":"${app.version}","environment":"${spring.profiles.active}"}'

  level:
    root: INFO
