spring:
  application:
    name: ${app.name}
  profiles:
    active: default
app:
  version: ${app.version}

server:
  port: 8484

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "prometheus" ]
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

logging:
  logging:
    logback:
      customFields: '{"app_name":"${spring.application.name}","app_version":"${app.version}","environment":"${spring.profiles.active}"}'

  level:
    root: INFO
